// English Language Pack
window.i18n_en = {
  clearAll: "🗑️ Clear All",
  waveformTitle: "🎧 Audio Waveform",
  inputTitle: "📝 Input",
  timelineTitle: "🎤 Lyrics Timeline",
  chooseAudio: "🎵 Choose Audio File",
  noFile: "No file selected",
  placeholder:
    "Paste your lyrics here...\n\nEach line will become a lyric entry.\nEmpty lines will be ignored.",
  loadLyrics: "📥 Load Lyrics",
  clear: "🧹 Clear",
  recordMode:
    "Record Mode: Press <kbd>Enter</kbd> while playing to sync lyrics",
  speed: "Speed:",
  copy: "📋 Copy to Clipboard",
  emptyTitle: "No lyrics loaded yet",
  emptyHint: 'Paste lyrics and click "Load Lyrics"',
  shortcutPlayPause: "Play/Pause",
  shortcutSync: "Sync current line",
  shortcutNav: "Navigate lyrics",
  shortcutSeek: "Seek ±2s",
  statusReady: "Ready - Load an audio file and lyrics to start",
  toastPasteFirst: "Please paste lyrics first!",
  toastLoadAudioFirst: "Please load an audio file first!",
  toastLoadLyricsFirst: "Please load lyrics first!",
  toastLoaded: (n) => `Loaded ${n} lines`,
  statusLyricsLoaded: (n) => `${n} lyrics loaded`,
  statusLoading: (name) => `Loading: ${name}`,
  toastAudioLoaded: "Audio loaded! Ready to sync.",
  statusAudioLoaded: "Audio loaded successfully",
  toastNoLyricsExport: "No lyrics to export!",
  toastCopied: "LRC copied to clipboard!",
  statusCopied: "LRC copied to clipboard",
  toastCopyFailed: "Failed to copy to clipboard",
  confirmClearAll: "Clear all lyrics and reset audio?",
  toastAllCleared: "All cleared",
  syncedLineStatus: (line, time) => `Synced line ${line}: ${time}`,
  lineSyncedToast: (line, time) => `Line ${line} synced to ${time}`,
  lineResetToast: (line) => `Line ${line} time reset`,
  lyricsCount: (synced, total) => `${synced}/${total} synced`,
  themeSystem: "System",
  themeDark: "Dark",
  themeLight: "Light",
  langEnglish: "English",
  langVietnamese: "Tiếng Việt",
  backwardTitle: "Backward 2s",
  forwardTitle: "Forward 2s",
  playPauseTitle: "Play/Pause",
  syncActionTitle: "Sync to current time",
  resetActionTitle: "Reset time",
  toastDataRestored: "Previous session restored",
  statusAudioRestored: "Audio restored from previous session",
  toastStorageError: "Failed to save audio to storage",
};
