// Vietnamese Language Pack
window.i18n_vi = {
  clearAll: "🗑️ Xóa hết",
  waveformTitle: "🎧 Dạng sóng âm thanh",
  inputTitle: "📝 Nhập liệu",
  timelineTitle: "🎤 Dòng lời",
  chooseAudio: "🎵 Chọn file nhạc",
  noFile: "Chưa chọn file",
  placeholder:
    "Dán lời bài hát vào đây...\n\nMỗi dòng sẽ thành một câu lyric.\nDòng trống sẽ bị bỏ qua.",
  loadLyrics: "📥 Tải lời",
  clear: "🧹 Xóa",
  recordMode: "Chế độ ghi: Nhấn <kbd>Enter</kbd> khi đang phát để đồng bộ",
  speed: "Tốc độ:",
  copy: "📋 Sao chép",
  emptyTitle: "Chưa có lời",
  emptyHint: 'Dán lời và bấm "Tải lời"',
  shortcutPlayPause: "Phát/Dừng",
  shortcutSync: "Đồng bộ dòng hiện tại",
  shortcutNav: "Di chuyển dòng",
  shortcutSeek: "Tua ±2 giây",
  statusReady: "Sẵn sàng - Chọn nhạc và dán lời để bắt đầu",
  toastPasteFirst: "Hãy dán lời bài hát trước!",
  toastLoadAudioFirst: "Hãy chọn file nhạc trước!",
  toastLoadLyricsFirst: "Hãy tải lời trước!",
  toastLoaded: (n) => `Đã tải ${n} dòng`,
  statusLyricsLoaded: (n) => `Đã tải ${n} dòng lời`,
  statusLoading: (name) => `Đang tải: ${name}`,
  toastAudioLoaded: "Đã tải nhạc! Sẵn sàng đồng bộ.",
  statusAudioLoaded: "Đã tải nhạc",
  toastNoLyricsExport: "Không có lời để xuất!",
  toastCopied: "Đã sao chép LRC!",
  statusCopied: "Đã sao chép LRC",
  toastCopyFailed: "Không thể sao chép",
  confirmClearAll: "Xóa toàn bộ lời và reset nhạc?",
  toastAllCleared: "Đã xóa hết",
  syncedLineStatus: (line, time) => `Đã đồng bộ dòng ${line}: ${time}`,
  lineSyncedToast: (line, time) => `Dòng ${line} -> ${time}`,
  lineResetToast: (line) => `Đã reset thời gian dòng ${line}`,
  lyricsCount: (synced, total) => `${synced}/${total} đã sync`,
  themeSystem: "Theo hệ thống",
  themeDark: "Tối",
  themeLight: "Sáng",
  langEnglish: "English",
  langVietnamese: "Tiếng Việt",
  backwardTitle: "Lùi 2s",
  forwardTitle: "Tiến 2s",
  playPauseTitle: "Phát/Dừng",
  syncActionTitle: "Đồng bộ theo thời gian hiện tại",
  resetActionTitle: "Reset thời gian",
  toastDataRestored: "Đã khôi phục phiên trước",
  statusAudioRestored: "Đã khôi phục audio từ phiên trước",
  toastStorageError: "Lỗi lưu audio vào bộ nhớ",
};
